version: "3.7"

services:
  etcd_snap:
    image: thomasjpfan/etcd-minio-snapshot:${TAG:-master}
    networks:
      - minio
    environment:
      - EMS_MINIO_ACCESS_KEY=MYACCESSKEY
      - EMS_MINIO_SECRET_KEY=MYSECRETKEY
      - EMS_MINIO_ENDPOINT=minio:9000
      - EMS_ETCD_SNAPSHOT_BUCKET=etcd
      - EMS_ETCD_OBJECT_NAME=hello.db

  etcd_no_snap:
    image: thomasjpfan/etcd-minio-snapshot:${TAG:-master}
    networks:
      - minio
    environment:
      - EMS_MINIO_ACCESS_KEY=MYACCESSKEY
      - EMS_MINIO_SECRET_KEY=MYSECRETKEY
      - EMS_MINIO_ENDPOINT=minio:9000
      - EMS_ETCD_SNAPSHOT_BUCKET=etcd
      - EMS_ETCD_OBJECT_NAME=doesnotexist.db

  minio:
    image: minio/minio:RELEASE.2018-09-12T18-49-56Z
    command: server /data
    networks:
      - minio
    environment:
      - MINIO_ACCESS_KEY=MYACCESSKEY
      - MINIO_SECRET_KEY=MYSECRETKEY
    volumes:
      - $PWD/testdata:/data

networks:
  ? minio
